apiVersion : apps/v1
kind: Deployment
metadata:
  name: "masterarbeitcluster-45c4"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "masterarbeitcluster-45c4"
  template:
    metadata:
      labels:
        app: "masterarbeitcluster-45c4"
    spec:
      containers:
        - name: "masterarbeitcluster-45c4"
          image: "masterimages.azurecr.io/masterarbeitcluster"
          ports:
          - containerPort: 8082