apiVersion: v1
kind: Service
metadata:
    name: "masterarbeitcluster-45c4"
    labels:
        app: "masterarbeitcluster-45c4"
spec:
    type: LoadBalancer
    ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: http
    selector:
        app: "masterarbeitcluster-45c4"